from __future__ import annotations

import unittest

from tests.common import ROOT  # noqa: F401
from agents_make.canon.app_spec import AppSpec, parse_spec_text
from agents_make.canon.lints import (
    lint_comment_policy_strict,
    lint_css_tokens_only,
    lint_envelope_conformance,
    lint_route_naming,
)


class CanonSpecAndLintsTests(unittest.TestCase):
    def test_parse_spec_text_accepts_valid_json(self) -> None:
        spec = parse_spec_text(
            '{"app_name":"Todo","feature_summary":"todo","entities":[{"name":"todo","fields":[{"name":"title","type":"str"}],"primary_key":"id"}],'
            '"routes":[{"method":"GET","path":"/api/todos","handler_name":"list_todos","entity":"todo","summary":"List"}],'
            '"views":[{"name":"todo-list","entity":"todo","purpose":"show todos"}],"notes":""}'
        )
        self.assertIsInstance(spec, AppSpec)
        self.assertEqual(spec.routes[0].path, "/api/todos")

    def test_route_and_envelope_lints_flag_mismatch(self) -> None:
        spec = AppSpec.model_validate(
            {
                "app_name": "Todo",
                "feature_summary": "todo",
                "entities": [{"name": "todo", "fields": [{"name": "title", "type": "str"}], "primary_key": "id"}],
                "routes": [{"method": "GET", "path": "/api/todos", "handler_name": "list_todos", "entity": "todo", "summary": "List"}],
                "views": [{"name": "todo-list", "entity": "todo", "purpose": "show todos"}],
                "notes": "",
            }
        )
        app_py = '"""m"""\n\nfrom flask import jsonify\n\n@app.get("/api/other")\ndef list_other():\n    return jsonify({"status": "ok"})\n'
        route_violations = lint_route_naming(app_py, spec)
        envelope_violations = lint_envelope_conformance(app_py)
        self.assertTrue(any("Missing expected route path" in row["message"] for row in route_violations))
        self.assertTrue(any(row["rule"] == "envelope_conformance" for row in envelope_violations))

    def test_css_and_comment_policy_lints(self) -> None:
        css_violations = lint_css_tokens_only(".x { color: #fff; }\n.y { background: red; }")
        self.assertGreaterEqual(len(css_violations), 1)
        self.assertEqual(lint_css_tokens_only('body { font-family: "Segoe UI", sans-serif; }'), [])

        app_py = (
            '"""Module."""\n\n'
            'def f(a: int, b: int) -> int:\n'
            '    """Doc.\n\nTwo paragraphs."""\n'
            '    return a + b\n'
        )
        js = "// generated by ai"
        comment_violations = lint_comment_policy_strict(app_py, js)
        self.assertTrue(any(row["rule"] == "comment_policy" for row in comment_violations))

    def test_route_lint_allows_scaffold_health_route(self) -> None:
        spec = AppSpec.model_validate(
            {
                "app_name": "Todo",
                "feature_summary": "todo",
                "entities": [{"name": "todo", "fields": [{"name": "title", "type": "str"}]}],
                "routes": [{"method": "GET", "path": "/api/todos", "handler_name": "list_todos", "entity": "todo"}],
                "views": [{"name": "todo-list", "entity": "todo"}],
                "notes": "",
            }
        )
        app_py = '@app.get("/api/todos")\ndef list_todos():\n    return ok_items([])\n\n@app.get("/api/health")\ndef health():\n    return ok_item({"status": "ok"})\n'
        self.assertEqual(lint_route_naming(app_py, spec), [])


if __name__ == "__main__":
    unittest.main()
