"""Canon policy lints for generated web-app artifacts."""

from __future__ import annotations

import ast
import re
from typing import Any

from .app_spec import AppSpec

_BANNED_PHRASE_RE = re.compile(
    r"\b(ai-generated|generated by|oathweaver wrote|written by ai|authored by ai)\b",
    re.IGNORECASE,
)

_COLOR_NAME_RE = re.compile(
    r"\b(?:red|blue|green|black|white|yellow|orange|purple|pink|gray|grey|brown)\b",
    re.IGNORECASE,
)


def lint_route_naming(app_py: str, spec: AppSpec) -> list[dict[str, Any]]:
    """Check route paths against spec routes."""
    violations: list[dict[str, Any]] = []
    expected_paths = {route.path for route in spec.routes}
    found_paths = set(
        match.group(2)
        for match in re.finditer(
            r"@app\.(?:route|get|post|put|delete)\(\s*([\"'])(/api/[^\"']+)\1",
            app_py,
        )
    )

    for missing in sorted(expected_paths - found_paths):
        violations.append(
            {
                "file": "app.py",
                "line": 1,
                "rule": "route_naming",
                "message": f"Missing expected route path: {missing}",
            }
        )
    for extra in sorted(found_paths - expected_paths):
        violations.append(
            {
                "file": "app.py",
                "line": 1,
                "rule": "route_naming",
                "message": f"Unexpected route path not declared in spec: {extra}",
            }
        )
    return violations


def lint_envelope_conformance(app_py: str) -> list[dict[str, Any]]:
    """Ensure route returns use ok_item / ok_items / err helpers."""
    violations: list[dict[str, Any]] = []
    for idx, line in enumerate(app_py.splitlines(), start=1):
        stripped = line.strip()
        if "return jsonify(" not in stripped:
            continue
        if "{\"item\"" in stripped or "{'item'" in stripped:
            continue
        if "{\"items\"" in stripped or "{'items'" in stripped:
            continue
        if "{\"error\"" in stripped or "{'error'" in stripped:
            continue
        violations.append(
            {
                "file": "app.py",
                "line": idx,
                "rule": "envelope",
                "message": "Raw jsonify return detected outside canonical helper shape.",
            }
        )
    return violations


def lint_css_tokens_only(feature_styles: str) -> list[dict[str, Any]]:
    """Require token usage in feature styles instead of direct colors."""
    violations: list[dict[str, Any]] = []
    for idx, line in enumerate(str(feature_styles or "").splitlines(), start=1):
        if re.search(r"#[0-9a-fA-F]{3,8}\b", line):
            violations.append(
                {
                    "file": "static/styles.css",
                    "line": idx,
                    "rule": "css_tokens",
                    "message": "Raw hex color found in feature styles. Use var(--neu-*) tokens.",
                }
            )
        if ":" in line and _COLOR_NAME_RE.search(line) and "var(--" not in line and "@" not in line:
            violations.append(
                {
                    "file": "static/styles.css",
                    "line": idx,
                    "rule": "css_tokens",
                    "message": "Named color found in feature styles. Use var(--neu-*) tokens.",
                }
            )
    return violations


def _function_has_full_type_hints(node: ast.AST) -> bool:
    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return False
    args = list(node.args.args) + list(node.args.kwonlyargs)
    for arg in args:
        if arg.annotation is None:
            return False
    if node.args.vararg and node.args.vararg.annotation is None:
        return False
    if node.args.kwarg and node.args.kwarg.annotation is None:
        return False
    return node.returns is not None


def lint_comment_policy_strict(app_py: str, app_js: str = "") -> list[dict[str, Any]]:
    """Run strict AST-based Python comment/docstring lint plus JS phrase guard."""
    violations: list[dict[str, Any]] = []

    try:
        module = ast.parse(app_py)
    except SyntaxError as exc:
        return [
            {
                "file": "app.py",
                "line": int(getattr(exc, "lineno", 1) or 1),
                "rule": "comment_policy",
                "message": f"Syntax error prevents AST lint: {exc}",
            }
        ]

    module_doc = ast.get_docstring(module, clean=False)
    if not module_doc:
        violations.append(
            {
                "file": "app.py",
                "line": 1,
                "rule": "comment_policy",
                "message": "Module docstring is required.",
            }
        )
    elif "\n" in module_doc.strip():
        violations.append(
            {
                "file": "app.py",
                "line": 1,
                "rule": "comment_policy",
                "message": "Module docstring must be one line.",
            }
        )

    for node in ast.walk(module):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        doc = ast.get_docstring(node, clean=False)
        statement_count = len(node.body)
        if statement_count >= 3 and not doc:
            violations.append(
                {
                    "file": "app.py",
                    "line": int(getattr(node, "lineno", 1) or 1),
                    "rule": "comment_policy",
                    "message": f"Function '{node.name}' needs a docstring.",
                }
            )
            continue
        if not doc:
            continue
        if "\n\n" in doc:
            violations.append(
                {
                    "file": "app.py",
                    "line": int(getattr(node, "lineno", 1) or 1),
                    "rule": "comment_policy",
                    "message": f"Function '{node.name}' docstring must not be multi-paragraph.",
                }
            )
        if _function_has_full_type_hints(node) and ("Args:" in doc or "Returns:" in doc):
            violations.append(
                {
                    "file": "app.py",
                    "line": int(getattr(node, "lineno", 1) or 1),
                    "rule": "comment_policy",
                    "message": f"Function '{node.name}' docstring should not include Args/Returns with full hints.",
                }
            )

    for idx, line in enumerate(app_py.splitlines(), start=1):
        if "#" not in line:
            continue
        if _BANNED_PHRASE_RE.search(line):
            violations.append(
                {
                    "file": "app.py",
                    "line": idx,
                    "rule": "comment_policy",
                    "message": "Banned attribution phrase found in Python comment.",
                }
            )

    for idx, line in enumerate(str(app_js or "").splitlines(), start=1):
        if "//" not in line and "/*" not in line and "*/" not in line:
            continue
        if _BANNED_PHRASE_RE.search(line):
            violations.append(
                {
                    "file": "static/app.js",
                    "line": idx,
                    "rule": "comment_policy",
                    "message": "Banned attribution phrase found in JavaScript comment.",
                }
            )

    return violations


def run_policy_lints(
    *,
    app_py: str,
    app_js: str,
    feature_styles: str,
    spec: AppSpec,
) -> list[dict[str, Any]]:
    """Run all canon policy lints and return structured violations."""
    violations: list[dict[str, Any]] = []
    violations.extend(lint_route_naming(app_py, spec))
    violations.extend(lint_envelope_conformance(app_py))
    violations.extend(lint_css_tokens_only(feature_styles))
    violations.extend(lint_comment_policy_strict(app_py, app_js))
    return violations
